### ISSUE TITLE
Weapon damage model

### ISSUE THREAD

**Issue by KaletheQuick** [ic3bug/Godot-Multiplayer-FPS#6]
Hi, I was poking around the code trying to learn it so I can contribute, and I noticed that the damage dealt was actually on each collider for the enemies, instead of stored with the weapon or projectile. This seemed odd to me and I was wondering if there was any particular reason it was done this way. Or if perhaps it was just quicker and adding in more weapons and items was not a concern.

**Comment by vec64** [comment]
Hello! I'm guessing you are referring to the damage multiplier for each hitbox. This way we can multiply the base weapon damage by some factor.

**Comment by KaletheQuick** [comment]
That would make sense, and I'm still trying to learn this codebase (Also I found Suzanne, scared the shit out of me).  But it does not seem to be used as a multiplier currently. Rather the calls below go to 'hit' which takes the value and applies it straight as damage.
Shotgun: character.hit(collider.damage, shooter)
Blaster Projectile: collider.get_owner().get_parent().hit(collider.damage, shooter)

This didn't really seem like an 'issue' but I'm not the most proficient with github and didn't know another way to contact you and start contributing and stuff.
